import SwiftUI
import HevSocks5Server

@MainActor
struct TrafficStatisticsView: View {
    let isVisible: Bool
    @Environment(\.scenePhase) private var scenePhase
    @ScaledMetric(relativeTo: .caption) private var labelColumnWidth: CGFloat = 40
    @State private var statistics = TrafficStatistics()
    @State private var clients = EndpointTrafficStatistics()
    @State private var clientsIncomplete = false

    var body: some View {
        let clientRows = clients.rows
        NavigationStack {
            Form {
                Section {
                    summary(statistics, id: "total")
                } header: {
                    Text("Total")
                        .font(.body.weight(.bold))
                        .textCase(nil)
                        .accessibilityIdentifier("total-title")
                }
                ForEach(clientRows) { client in
                    Section {
                        summary(client.traffic, id: "client-\(client.id)")
                    } header: {
                        Text(client.address)
                            .font(.body.weight(.bold))
                            .textCase(nil)
                            .accessibilityIdentifier("client-\(client.id)")
                    }
                }
                if clientRows.isEmpty || clientsIncomplete {
                    Section {
                        if clientRows.isEmpty {
                            Text("No peer socket I/O recorded yet.")
                                .foregroundStyle(.secondary)
                        }
                        if clientsIncomplete {
                            Text("Some peer rows are awaiting an update.")
                                .font(.footnote)
                        }
                    }
                }
                Section {
                    Text("Spd.: average successful socket I/O over the last sample (about 1 second), in bits per second; not link capacity.")
                        .accessibilityIdentifier("measurement-speed")
                    Text("Vol.: successful server-owned TCP/UDP socket bytes since this process started. Server Stop/Start retains totals. Both client and destination peers are included.")
                        .accessibilityIdentifier("measurement-volume")
                    Text("Peer viewpoint: In is bytes the OS accepted toward that IP; Out is bytes this server consumed from that IP. Includes SOCKS negotiation, authentication, framing and consumed rejected input. A write is not proof of remote delivery.")
                    Text("Total sums peer endpoints, not unique relayed content. LAN and Internet peers use the same rules. Direct traffic bypassing this server is not observed. IPs are endpoints, not device identities. Unresolved peer IPs appear as Unattributed. Independent live snapshots can briefly differ.")
                    Text("No IP/TCP/UDP headers generated by the OS, ACKs, kernel retransmissions, system-resolver internals or interface totals are measured. This is not IPFIX IP octets. SI units, two decimals; visible sampling pauses while inactive without resetting native counters.")
                }
                .font(.footnote)
                .foregroundStyle(.secondary)
            }
            .navigationTitle("Statistics")
        }
        .task(id: isVisible && scenePhase == .active) {
            guard isVisible && scenePhase == .active else { return }
            statistics = TrafficStatistics()
            clients = EndpointTrafficStatistics()
            clientsIncomplete = false
            sample()
            while !Task.isCancelled {
                do { try await Task.sleep(for: .seconds(1)) }
                catch { return }
                guard !Task.isCancelled else { return }
                sample()
            }
        }
    }

    /// One shared table for the aggregate and every registered client.
    private func summary(_ statistics: TrafficStatistics, id: String) -> some View {
        Grid(alignment: .leading, horizontalSpacing: 0, verticalSpacing: 0) {
            GridRow {
                rowLabel(" ").accessibilityHidden(true)
                tableCell("In", id: "\(id)-column-in", bold: true)
                tableCell("Out", id: "\(id)-column-out", bold: true)
                tableCell("In + Out", id: "\(id)-column-sum", bold: true)
            }
            Color(white: 0.82)
                .frame(height: 1)
                .gridCellUnsizedAxes(.horizontal)
                .accessibilityHidden(true)
            GridRow {
                rowLabel("Spd.")
                    .accessibilityIdentifier("\(id)-label-speed")
                tableCell(TrafficStatistics.speed(statistics.receiveRate), id: "\(id)-speed-in")
                tableCell(TrafficStatistics.speed(statistics.sendRate), id: "\(id)-speed-out")
                tableCell(TrafficStatistics.speed(statistics.sumRate), id: "\(id)-speed-sum")
            }
            GridRow {
                rowLabel("Vol.")
                    .accessibilityIdentifier("\(id)-label-volume")
                tableCell(TrafficStatistics.capacity(Double(statistics.received)), id: "\(id)-usage-in")
                tableCell(TrafficStatistics.capacity(Double(statistics.sent)), id: "\(id)-usage-out")
                tableCell(TrafficStatistics.capacity(
                    Double(statistics.received) + Double(statistics.sent)), id: "\(id)-usage-sum")
            }
        }
        .font(.callout)
        .foregroundStyle(.black)
        .background(.white)
        .listRowBackground(Color.white)
        .listRowInsets(EdgeInsets(top: 4, leading: 12, bottom: 4, trailing: 12))
    }

    private func rowLabel(_ text: String) -> some View {
        Text(text)
            .fontWeight(.bold)
            .fixedSize(horizontal: true, vertical: false)
            .padding(.vertical, 8)
            .padding(.trailing, 8)
            .frame(width: labelColumnWidth, alignment: .leading)
            .overlay(alignment: .trailing) {
                Color(white: 0.82).frame(width: 1)
            }
    }

    private func tableCell(_ text: String, id: String, bold: Bool = false) -> some View {
        Text(text)
            .fontWeight(bold ? .bold : .regular)
            .monospacedDigit()
            .lineLimit(1)
            .minimumScaleFactor(0.5)
            .padding(.vertical, 8)
            .padding(.horizontal, 4)
            .frame(maxWidth: .infinity, alignment: .center)
            .accessibilityIdentifier(id)
    }

    private func sample() {
        var received: UInt64 = 0
        var sent: UInt64 = 0
        hev_socks5_server_endpoint_stats(&received, &sent)
        // Concurrent registration can defer row updates across multiple samples;
        // keep cached rows while subsequent samples retry the bounded copy.
        let capacity = hev_socks5_server_endpoint_rows(nil, 0)
        var rows = [HevSocks5EndpointStats](repeating: HevSocks5EndpointStats(), count: capacity)
        let required = rows.withUnsafeMutableBufferPointer {
            hev_socks5_server_endpoint_rows($0.baseAddress, $0.count)
        }
        clientsIncomplete = required > capacity
        let time = ProcessInfo.processInfo.systemUptime
        statistics.sample(received: received, sent: sent, at: time)
        // Build one value snapshot before publishing; per-row State writes can
        // repeatedly copy the dictionary and invalidate the same view state.
        var sampledClients = clients
        for var row in rows.prefix(min(capacity, required)) {
            let address = withUnsafePointer(to: &row.address) {
                $0.withMemoryRebound(to: CChar.self, capacity: 64) { String(cString: $0) }
            }
            sampledClients.sample(id: row.id, address: address, received: row.received,
                                 sent: row.sent, at: time)
        }
        clients = sampledClients
    }
}
